### PR TITLE
Plot midline and allow changing sample

### PR DESCRIPTION
**Pull request by cmdcolin**
This demo allows selecting the sample from the dialog box, and drawing the average of all the bins as an extra line in the multibigwig

localhost_jbrowse__data=plugins%2Fvcfview%2Ftest%2Fdata loc=20%3A34712117 54129455 tracks=DNA%2Ctrio%20vcf%20multivcf highlight=

No normalization applied

Just trying to get the right ideas before adding refactoring and making code cleaner...

### CODE REVIEW

**Comment by cmdcolin** [comment]
Some additional work on optimizing may come down the line in the future also https://github.com/GMOD/tabix-js/pull/117

**Comment by cmdcolin** [comment]
@arpanda any thoughts on this? I started also a port to jbrowse 2, just to see how it performs. It doesn't have multibigwig plotting or the average line but just as an example https://github.com/cmdcolin/jbrowse-plugin-cnvplotter

**Comment by arpanda** [comment]
@cmdcolin This is great. We can see how its works in JBrowse2. However, I can't see the screenshot in the GitHub link. I have not installed JBrowse2 and not sure about the link for it.

**Comment by cmdcolin** [comment]
Added the screenshot, it's quite basic but here https://github.com/cmdcolin/jbrowse-plugin-cnvplotter

I think adding other features like the average line wouldn't be "too hard" but we are also racing with a lot of tasks hehe

**Pull request merged**
